/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package tragamonedas;

import javax.swing.JOptionPane;

/**
 *
 * @author mateo
 */
public class Interfaz extends javax.swing.JFrame {
    
    private boolean stopThreads = false;
    //se crean arreglo de las figuras que se van a mostrar en los rollos
    Figura[] figura = new Figura[4];
    
    MaquinaTragaMonedas maquina = new MaquinaTragaMonedas();

    /**
     * Creates new form NewJFrame
     */
    public Interfaz() {
        initComponents();
        //para eleminar la opciones agradar el tamanio a la ventana principal

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        comenzarJuego = new javax.swing.JToggleButton();
        PUNTOS = new javax.swing.JToggleButton();
        SALIDA = new javax.swing.JToggleButton();
        Detener = new javax.swing.JToggleButton();
        Global = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        Rodillo1 = new javax.swing.JLabel();
        Rodillo2 = new javax.swing.JLabel();
        Rodillo3 = new javax.swing.JLabel();
        jOptionPane = new javax.swing.JOptionPane();
        jTextField1 = new javax.swing.JTextField();
        Fondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        comenzarJuego.setText("JUGAR");
        comenzarJuego.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comenzarJuegoActionPerformed(evt);
            }
        });
        getContentPane().add(comenzarJuego, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 220, 111, -1));

        PUNTOS.setText("Sistema De Puntos");
        PUNTOS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PUNTOSActionPerformed(evt);
            }
        });
        getContentPane().add(PUNTOS, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 220, -1, -1));

        SALIDA.setText("SALIR");
        SALIDA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SALIDAActionPerformed(evt);
            }
        });
        getContentPane().add(SALIDA, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 10, -1, -1));

        Detener.setText("Detener");
        Detener.setToolTipText("");
        Detener.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DetenerActionPerformed(evt);
            }
        });
        getContentPane().add(Detener, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 180, -1, -1));

        Global.setText("puntaje");
        Global.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GlobalActionPerformed(evt);
            }
        });
        getContentPane().add(Global, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, -1, -1));

        Rodillo1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/4.png"))); // NOI18N

        Rodillo2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/2.png"))); // NOI18N

        Rodillo3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/1.png"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(Rodillo1)
                        .addGap(18, 18, 18)
                        .addComponent(Rodillo2)
                        .addGap(18, 18, 18)
                        .addComponent(Rodillo3))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jOptionPane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(12, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(Rodillo1)
                    .addComponent(Rodillo2)
                    .addComponent(Rodillo3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jOptionPane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 70, 280, 90));

        jTextField1.setText("Mateo y Maria");
        getContentPane().add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 30, -1, -1));

        Fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/OIP (7).jpg"))); // NOI18N
        getContentPane().add(Fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents
    //accione que hace el boton de jugar
    private void comenzarJuegoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comenzarJuegoActionPerformed
        // TODO add your handling code here:
        
        //se indica que cada figura representa un rollo
       figura[1] = new Figura(1, stopThreads);
       figura[2] = new Figura(2, stopThreads);
       figura[3] = new Figura(3, stopThreads); 
        
        //se ejecuta los metodos de cada arreglo en forma separada
        figura[1].start();
        figura[2].start();
        figura[3].start();
    }//GEN-LAST:event_comenzarJuegoActionPerformed
    //lo que muestra cunado se oprime el sistema de puntos
    private void PUNTOSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PUNTOSActionPerformed
        // TODO add your handling code here:
        
        //se muestra el puntajes posibles
        JOptionPane.showMessageDialog(null, """
                           \u2981\tSi las tres figuras son iguales, gana $1000.
                           \u2981\tSi hay dos figuras iguales, gana $300.
                           \u2981\tEn cualquier otro caso, pierde -$50.""");
    }//GEN-LAST:event_PUNTOSActionPerformed
     //boton para salir
    private void SALIDAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SALIDAActionPerformed
        // Boton para salida
        System.exit(0);
    }//GEN-LAST:event_SALIDAActionPerformed

    private void DetenerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DetenerActionPerformed
        // TODO add your handling code here:
        // Botón para detener el juego
        //se detiene los metdos de las figuras al mismo tiempo
        //con una metedo llamado detener
        
        
        for (int i = 1; i < figura.length; i++) {
            figura[i].detener();
        }
        
        //se va mostrar lo que se ha conseguido
        int num;
        num = maquina.contarFigurasIguales(figura);
        
       maquina.puntajeGlobal += num;
        switch (num) {
            case 1000 -> JOptionPane.showMessageDialog(null, "Felicitaciones, has ganado! \n"+ num +"   puntos");
            case 300 -> JOptionPane.showMessageDialog(null, "Felicitaciones, has Consegudo 2 figuras! \n"+num+"   puntos");
            default -> JOptionPane.showMessageDialog(null, "Inteero de nuevo, has Consegudo 1 figuras! \n"+num+"   puntos");
        }
    }//GEN-LAST:event_DetenerActionPerformed

    private void GlobalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GlobalActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(null, maquina.puntajeGlobal);
    }//GEN-LAST:event_GlobalActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new Interfaz().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton Detener;
    private javax.swing.JLabel Fondo;
    private javax.swing.JButton Global;
    private javax.swing.JToggleButton PUNTOS;
    public static javax.swing.JLabel Rodillo1;
    public static javax.swing.JLabel Rodillo2;
    public static javax.swing.JLabel Rodillo3;
    private javax.swing.JToggleButton SALIDA;
    private javax.swing.JToggleButton comenzarJuego;
    private javax.swing.JOptionPane jOptionPane;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables

    private void seclocationRelativeTo() {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    
    }
    
}
